apiVersion: b2.m.crossplane.io/v1alpha1
kind: ApplicationKey
metadata:
  name: example-crossplane-key
  namespace: crossplane-system
spec:
  forProvider:
    keyName: example-crossplane-key
    capabilities:
      - readFiles
    bucketRef:
      name: example-crossplane-bucket
  providerConfigRef:
    kind: ProviderConfig
    name: default
  writeConnectionSecretToRef:
    name: example-crossplane-key
